symfony/src/Entity/Tarifer.php
<?php

namespace App\Entity;

use App\Repository\TariferRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TariferRepository::class)
 */
class Tarifer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $tarif;

    /**
     * @ORM\ManyToOne(targetEntity=Type::class, inversedBy="tarifers")
     */
    private $Type;

    /**
     * @ORM\ManyToOne(targetEntity=Periode::class, inversedBy="tarifers")
     */
    private $Periode;

    /**
     * @ORM\ManyToOne(targetEntity=Liaison::class, inversedBy="tarifers")
     */
    private $Liaison;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTarif(): ?float
    {
        return $this->tarif;
    }

    public function setTarif(float $tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->Type;
    }

    public function setType(?Type $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getPeriode(): ?Periode
    {
        return $this->Periode;
    }

    public function setPeriode(?Periode $Periode): self
    {
        $this->Periode = $Periode;

        return $this;
    }

    public function getLiaison(): ?Liaison
    {
        return $this->Liaison;
    }

    public function setLiaison(?Liaison $Liaison): self
    {
        $this->Liaison = $Liaison;

        return $this;
    }
}

symfony/src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Traversee;
use App\Form\TraverseRechercheType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AccueilController extends AbstractController
{


    /**
     * @Route("/", name="home")
     */
    public function home(Request $request) {
        $traversee = new Traversee();
        
        $form = $this->createForm(TraverseRechercheType::class, $traversee);
        $form->handleRequest($request);

        $traversees = $this->getDoctrine()->getManager()->getRepository(Traversee::class)->getAll();

        return $this->render('accueil/accueil.html.twig', array('form'=> $form->createView(), 'traversees' => $traversees));
    }

}

symfony/templates/accueil/accueil.html.twig
{% extends 'base.html.twig' %}
{% block head %}
{% endblock %}

{% block title %}Accueil - Sicily Lines{% endblock %}

{% block content %}
<h1 class="pageTitle">Sicily lines</h1>
<div class="container">
    {{ form_start(form)}}

</div>
<div class="container-xl">
    
        <div class="col-md-12 m-auto">
        <div class="row justify-content-center">
            {% for traversee in traversees %}
                <div class="card m-3" style="width: 18rem;">
                    <img class="card-img-top" src="{{ asset('assets/images/boatImg.jpg')}}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{traversee.getLiaison.portDepart.nom}} -> {{traversee.liaison.portArrivee.nom}}</h5>
                        <div class="d-flex justify-content-between card-text">
                            <span class="h5"><b>{{traversee.date | date('j/m/t')}}</b></span>
                            <span class="h5"><b>{{traversee.heure | date('h')}} h {{traversee.heure | date('m')}}</b></span>
                        </div>
                        <p><b>Bateau : {{traversee.bateau.nom}}</b></p>
                        
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    
</div>
{% endblock %}
    

symfony/templates/accueil/index.html.twig
{% extends 'base.html.twig' %}
{% block head %}

{% endblock %}

{% block title %}Hello C'est le projet Sicily{% endblock %}

{% block content %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
{%set nom = "Pedro (no no Jose)"%}
<div class="example-wrapper">
    <h1>Bienvenue sur le site SicilyLines {{nom}}! ✅</h1>

    This friendly message is coming from:
    
    <ul>
        <li>Your controller at <code><a href="{{ '/var/www/html/projetSicily/src/Controller/AccueilController.php'|file_link(0) }}">src/Controller/AccueilController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/var/www/html/projetSicily/templates/accueil/index.html.twig'|file_link(0) }}">templates/accueil/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}
    